### ISSUE TITLE
client error: cannot get any image

### ISSUE THREAD

**Issue by ttpro1995** [ayastreb/bandwidth-hero-proxy#15]
This is a error I only met once, on my Ubuntu laptop. I use the same server that work on other of my machine (both Ubuntu and Windows, both firefox and chrome)

What happen: 
Chrome, FIrefox on Ubuntu OS my laptop cannot get any image. 
(Ubuntu on others machine worked, Windows on the same laptop worked)

When I check the console, it said: 
Failed to load resource: the server responded with a status of 404 ()
With the url   
`http://206.189.84.191:26465/%20?url=http%3A%2F%2F206.189.84.191%3A26465%2F%2520%3Furl%3Dhttps%253A%252F%252Fi.imgur.com%252FaVfWYVl.jpg%26l%3D40&l=40`

When I copy and paste the url on browser address bar, it say:
`Cannot GET /%20`

**Comment by ttpro1995** [comment]
delete the plugin, reinstall fixed it... 
no idea how

**Comment by ayastreb** [comment]
Looks like there was a space at the end of the proxy URL
