### ISSUE TITLE
Cannot get image on some HTTPS site (example: this site github ) 

### ISSUE THREAD

**Issue by ttpro1995** [ayastreb/bandwidth-hero-proxy#16]
`Mixed Content: The page at 'https://github.com/ayastreb/bandwidth-hero-proxy' was loaded over HTTPS, but requested an insecure image 'http://206.189.84.191:26465/?url=https%3A%2F%2Fassets-cdn.github.com%2Fimages%2Fspinners%2Foctocat-spinner-128.gif&bw=0&l=40'. This request has been blocked; the content must be served over HTTPS.`

I host on http://206.189.84.191:26465  (Dokku server without domain name) because I is somewhat expensive to buy (and time consuming to setup) a name domain. 

Screenshot 
![Alt text](https://prnt.sc/k3o6e5)
 
By the way, Facebook work just fine.

**Comment by ttpro1995** [comment]
I build on heroku (free dyno) which also give me SSL can fix the problem 
https://bandwidth-hero-proxy-ttpro1995.herokuapp.com/ 

However, as self-host app on Dokku, I think I must get the domain name (not so free) and free SSL (with let's encrypt) and sometime to config Dokku to fix the problem

**Comment by ayastreb** [comment]
Yes, the proxy needs to run on HTTPS to work on secure pages. You need a domain name (you can get one pretty cheap now, e.g. there are $0.88 domains at [namecheap](https://www.namecheap.com/promos/amazing88s.aspx))
For HTTPS you could also use [CloudFlare ](https://www.cloudflare.com/)with your domain name - they provide free ssl and caching

**Comment by ttpro1995** [comment]
Heroku is seem to be slower than without using it. Perhaps I have to set up the SSL for my own server.

**Comment by ttpro1995** [comment]
I set https on Dokku using Let's encrypt
https://bandwidth-hero-proxy.thaithienapp.club/  (you can share with me it you can't manage to host one)

In order to set HTTPS on Dokku, I need: 
1. any domain name (so buy a cheapest possible)
2. set domain name on dokku
```
dokku domains:add-global yourdomain.tld
dokku domains:add myapp myapp.yourdomain.tld
dokku domains:enable myapp
```
2. Use Let's encrypt plugin https://github.com/dokku/dokku-letsencrypt

**Comment by jarrodoxical** [comment]
You don't need a domain name. Self-hosted users can easily auto generate a self-signed certificate using openSSL-cli by updating `server.js` 

```
#!/usr/bin/env node
'use strict'
const authenticate = require('./src/authenticate');
const params = require('./src/params');
const proxy = require('./src/proxy');
const app = require('express')();
const fs = require( 'fs' );

const protocol = process.env.PROTOCOL || 'https',
port = process.env.PORT || '8080',
host = process.env.HOST || '0.0.0.0'; //use localhost if you VPN and dont need exposure

let server;

app.enable('trust proxy')
app.get('/', authenticate, params, proxy)
app.get('/favicon.ico', (req, res) => res.status(204).end())

// Start a development HTTPS server.
if ( protocol === 'https' ) {
	const { execSync } = require( 'child_process' );
	const execOptions = { encoding: 'utf-8', windowsHide: true };
	let key = './src/key.pem';
	let certificate = './src/certificate.pem';
	
	if ( ! fs.existsSync( key ) || ! fs.existsSync( certificate ) ) {
		try {
			execSync( 'openssl version', execOptions );
			execSync(
				`openssl req -x509 -newkey rsa:2048 -keyout ./src/key.tmp.pem -out ${ certificate } -days 365 -nodes -subj "/C=US/ST=Foo/L=Bar/O=Baz/CN=localhost"`,
				execOptions
			);
			execSync( `openssl rsa -in ./src/key.tmp.pem -out ${ key }`, execOptions );
			execSync( 'rm ./src/key.tmp.pem', execOptions );
		} catch ( error ) {
			console.error( error );
		}
	}
	const options = {
		key: fs.readFileSync( key ),
		cert: fs.readFileSync( certificate ),
		passphrase : 'password'
    };
    server = require( 'https' ).createServer( options, app );
} else {
    server = require( 'http' ).createServer( app );
}

server.listen( { port, host }, function() {
    console.log(`Listening on ${port}`)
} );
```

Requires sudo to write the cert files on first run `nvm use 8.6.0; sudo node server.js` then `ctrl-c` Now in the same command prompt enter `PORT=8444 LOGIN=admin PASSWORD=admin pm2 start server.js` to keep it running

Be sure to visit `https://yourserverip:8444/` in browser to add the security exception and use standard login format in the browser add-on `https://admin:admin@yourserverip:8444/`
