### ISSUE TITLE
Password protect proxy server

### ISSUE THREAD

**Issue by ayastreb** [ayastreb/bandwidth-hero-proxy#2]
Need to add ability to password protect the proxy server for users running their own private instance.

**Comment by hpvd** [comment]
+1

**Comment by alexisHetic** [comment]
+1

**Comment by ayastreb** [comment]
Implemented. You can now set `LOGIN` and `PASSWORD` env variables and the app will require basic HTTP auth with those credentials.
I've also updated Heroku deploy template, so users can set login/pass from Heroku interface while deploying the app.
