### ISSUE TITLE
Enable progressive JPEG

### ISSUE THREAD

**Issue by niutech** [ayastreb/bandwidth-hero-proxy#5]
According to the [sharp JPEG output options](http://sharp.dimens.io/en/stable/api-output/#jpeg), the default option is baseline, not progressive JPEG. Could you enable `progressive` and possibly `optimiseScans` as well for faster loading images? Thanks!

**Comment by sunk818** [comment]
I like the of "progressive JPEG" as well. I think the GIF equivalent would be interlaced. On extremely low bandwidth systems, having the interlaced provides a placeholder sooner and a quicker clue to the final image. You could potentially load 50% of a progressive JPEG a blurred image to save a lot of bandwidth.

**Comment by ayastreb** [comment]
Enabled `progressive` and `optimizeScans` options.

**Comment by ttpro1995** [comment]
how to do this ? 

`Enabled progressive and optimizeScans options.`
