### ISSUE TITLE
Suddenly stopped providing webp compression for waterfox (despite it having native webp support)

### ISSUE THREAD

**Issue by Tomatoide** [ayastreb/bandwidth-hero-proxy#7]
Waterfox supports webp, but looks like webp compression has been removed entirely for firefox (waterfox has started showing black backgrounds after it didn't have that issue at all), I suggest keeping webp support but for waterfox ua only. Thanks.

**Comment by ayastreb** [comment]
I've tried to determine if webp is supported based on `Accepts` header, but seems like it's not reliable.
I've rolled it back to old version
